 pipeline {
    agent any

    // This block links the tool you configured in Jenkins UI to this script
    tools {
        // The name here MUST match the name in "Manage Jenkins > Tools"
        sonarScanner 'sonar-scanner' 
    }

    environment {
        APP_NAME        = "todo-app"
        IMAGE_NAME      = "todo-app:latest"
        SONAR_HOST_URL  = "http://192.168.0.88:9000"
        SONAR_PROJECT   = "todo-app"
        KUBECONFIG      = "/var/lib/jenkins/.kube/config"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Cloning source code..."
                git branch: 'main', url: "https://github.com/RohanPatil198/CDAC_Project.git"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh "docker build -t ${IMAGE_NAME} -f docker/Dockerfile ."
            }
        }

        stage('Trivy Image Scan') {
            steps {
                echo "Scanning Docker image with Trivy..."
                sh """
                    trivy image --exit-code 0 --severity LOW,MEDIUM ${IMAGE_NAME}
                    trivy image --exit-code 1 --severity HIGH,CRITICAL ${IMAGE_NAME} || true
                """
            }
        }

        stage('SonarQube Code Scan') {
            steps {
                echo "Running SonarQube analysis..."
                // withSonarQubeEnv allows Jenkins to use the Server URL/Token from Global System Config
                // The name 'SonarQube' must match the name in Manage Jenkins > System
                script {
                    sh """
                        sonar-scanner \
                        -Dsonar.projectKey=${SONAR_PROJECT} \
                        -Dsonar.sources=app \
                        -Dsonar.host.url=${SONAR_HOST_URL}
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
    }
}
